name: Daily Commit

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '0 8 * * *' # runs daily at 8 AM UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a daily commit
        run: |
          echo "// Daily update: $(date)" >> daily-log.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit: $(date)"
          git push
