name: Daily Commit

on:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make a dummy change and commit
        run: |
          echo "Updated on $(date)" >> daily-log.txt
          git config --global user.name "Mukund"
          git config --global user.email "23f2004624@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily commit"
          git push
